export const iconsClass = [
  'home',
  'check',
  'phone',
  'magnifying-glass',
  'user',
  'star',
  'image',
  'heart',
  'pen-nib',
  'paperclip',
  'wand-magic-sparkles',
  'music',
  'camera-retro',
  'shield-halved',
  'face-smile',
];
